import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:stockflowkp/services/api_service.dart';

import 'package:stockflowkp/services/database_service.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class DukaProductsPage extends StatefulWidget {
  final int dukaId;
  final String? dukaName;

  const DukaProductsPage({super.key, required this.dukaId, this.dukaName});

  @override
  State<DukaProductsPage> createState() => _DukaProductsPageState();
}

class _DukaProductsPageState extends State<DukaProductsPage> {
  final ApiService _apiService = ApiService();
  final DatabaseService _dbService = DatabaseService();
  bool _isLoading = true;

  String? _error;
  Map<String, dynamic>? _data;
  List<dynamic> _products = [];
  List<dynamic> _filteredProducts = [];
  List<dynamic> _categories = [];
  List<dynamic> _allStocks = [];
  String? _token;

  String _searchQuery = '';
  String? _selectedCategory;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    print("there is any error");
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final userData = await _dbService.getUserData();
      print(userData);
      if (userData != null && userData['data'] != null) {
        final token = userData['data']['token'];
        _token = token;
        final response = await _apiService.getDukaProducts(
          widget.dukaId,
          token,
        );

        if (mounted) {
          setState(() {
            _data = response['data'];
            _products = _data?['products'] ?? [];
            _categories = _data?['categories'] ?? [];
            _allStocks = _data?['inventory_details']?['stocks'] ?? [];
            _filteredProducts = _products;
            _isLoading = false;
          });
        }
      } else {
        if (mounted) {
          setState(() {
            _error = "User session not found.";
            _isLoading = false;
          });
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = "Failed to load products: $e";
          _isLoading = false;
        });
      }
    }
  }

  void _filterProducts() {
    setState(() {
      _filteredProducts =
          _products.where((product) {
            final matchesSearch =
                product['name'].toString().toLowerCase().contains(
                  _searchQuery.toLowerCase(),
                ) ||
                (product['sku']?.toString().toLowerCase().contains(
                      _searchQuery.toLowerCase(),
                    ) ??
                    false);

            final matchesCategory =
                _selectedCategory == null ||
                product['category_name'] == _selectedCategory;

            return matchesSearch && matchesCategory;
          }).toList();
    });
  }

  String _formatCurrency(dynamic amount) {
    final formatter = NumberFormat.currency(symbol: 'Tsh ', decimalDigits: 0);
    return formatter.format(amount ?? 0);
  }

  Future<void> _generatePdf() async {
    final pdf = pw.Document();
    final dukaTitle = widget.dukaName ?? "Duka Shop";

    // Define custom colors
    final baseColor = PdfColors.blue900;
    final accentColor = PdfColors.blue600;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        footer: (pw.Context context) {
          return pw.Container(
            decoration: const pw.BoxDecoration(
              border: pw.Border(top: pw.BorderSide(color: PdfColors.grey400)),
            ),
            padding: const pw.EdgeInsets.only(top: 10),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by StockFlow',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          );
        },
        build: (pw.Context context) {
          return [
            // Header
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(color: baseColor, width: 2),
                ),
              ),
              padding: const pw.EdgeInsets.only(bottom: 10),
              margin: const pw.EdgeInsets.only(bottom: 20),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        dukaTitle,
                        style: pw.TextStyle(
                          fontSize: 26,
                          fontWeight: pw.FontWeight.bold,
                          color: baseColor,
                        ),
                      ),
                      pw.Text(
                        'Inventory Stock Report',
                        style: pw.TextStyle(fontSize: 16, color: accentColor),
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        'Date: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                      pw.Text(
                        'Time: ${DateFormat('HH:mm').format(DateTime.now())}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // Stats Summary
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _buildPdfStatCard(
                  'Total Products',
                  '${_filteredProducts.length}',
                  baseColor,
                ),
                _buildPdfStatCard(
                  'Total Stock',
                  '${_calcTotalStock()}',
                  baseColor,
                ),
                _buildPdfStatCard(
                  'Total Value',
                  _formatCurrency(_calcTotalStockValue()),
                  baseColor,
                ),
              ],
            ),
            pw.SizedBox(height: 20),

            // Table
            pw.Table.fromTextArray(
              context: context,
              headers: [
                'Product Name',
                'Category',
                'SKU',
                'Stock',
                'Unit',
                'Price',
              ],
              data:
                  _filteredProducts.map((product) {
                    return [
                      product['name']?.toString() ?? '',
                      product['category_name']?.toString() ?? '-',
                      product['sku']?.toString() ?? '-',
                      (product['current_stock'] ?? 0).toString(),
                      product['unit']?.toString() ?? '',
                      _formatCurrency(product['selling_price']),
                    ];
                  }).toList(),
              border: null,
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: pw.BoxDecoration(color: baseColor),
              rowDecoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                ),
              ),
              cellPadding: const pw.EdgeInsets.symmetric(
                horizontal: 10,
                vertical: 8,
              ),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerLeft,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.centerLeft,
                5: pw.Alignment.centerRight,
              },
            ),
            pw.SizedBox(height: 10),
            pw.Container(
              alignment: pw.Alignment.centerRight,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                mainAxisSize: pw.MainAxisSize.min,
                children: [
                  pw.Text(
                    'Total Stock Value: ',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.Text(
                    _formatCurrency(_calcTotalStockValue()),
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: baseColor,
                      fontSize: 14,
                    ),
                  ),
                ],
              ),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Stock_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  pw.Widget _buildPdfStatCard(String label, String value, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      ],
    );
  }

  int _calcTotalStock() {
    int total = 0;
    for (var p in _filteredProducts) {
      total += (p['current_stock'] as num? ?? 0).toInt();
    }
    return total;
  }

  double _calcTotalStockValue() {
    double total = 0;
    for (var p in _filteredProducts) {
      final stock = (p['current_stock'] as num? ?? 0).toDouble();
      final price = (p['selling_price'] as num? ?? 0).toDouble();
      total += stock * price;
    }
    return total;
  }

  void _showProductDetails(Map<String, dynamic> product) {
    if (_token == null) return;

    final productId = product['id'];
    // Filter stocks for this product from the master list
    final productStocks =
        _allStocks.where((stock) => stock['product_id'] == productId).toList();

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder:
          (context) => ProductDetailsSheet(
            product: product,
            initialStocks: productStocks,
            token: _token!,
          ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Center(
        child: CircularProgressIndicator(color: Color(0xFF4BB4FF)),
      );
    }

    if (_error != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.error_outline, color: Colors.redAccent, size: 48),
            const SizedBox(height: 16),
            Text(
              _error!,
              textAlign: TextAlign.center,
              style: GoogleFonts.plusJakartaSans(color: Colors.white70),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: _loadData,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF4BB4FF),
              ),
              child: const Text("Retry"),
            ),
          ],
        ),
      );
    }

    return Column(
      children: [
        // Search and Filter Bar
        Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              // PDF Export Button and Title
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    "Products",
                    style: GoogleFonts.plusJakartaSans(
                      color: Colors.white,
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  ElevatedButton.icon(
                    onPressed: _generatePdf,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF4BB4FF),
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    icon: const Icon(Icons.picture_as_pdf, size: 20),
                    label: const Text("PDF"),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              TextField(
                onChanged: (value) {
                  _searchQuery = value;
                  _filterProducts();
                },
                style: const TextStyle(color: Colors.white),
                decoration: InputDecoration(
                  hintText: 'Search products...',
                  hintStyle: const TextStyle(color: Colors.white38),
                  prefixIcon: const Icon(Icons.search, color: Colors.white38),
                  filled: true,
                  fillColor: Colors.white.withOpacity(0.05),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide.none,
                  ),
                ),
              ),
              const SizedBox(height: 12),
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: [
                    FilterChip(
                      label: const Text('All'),
                      selected: _selectedCategory == null,
                      onSelected: (selected) {
                        setState(() {
                          _selectedCategory = null;
                          _filterProducts();
                        });
                      },
                      backgroundColor: Colors.white.withOpacity(0.05),
                      selectedColor: const Color(0xFF4BB4FF).withOpacity(0.2),
                      labelStyle: TextStyle(
                        color:
                            _selectedCategory == null
                                ? const Color(0xFF4BB4FF)
                                : Colors.white70,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                        side: BorderSide(
                          color:
                              _selectedCategory == null
                                  ? const Color(0xFF4BB4FF)
                                  : Colors.transparent,
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    ..._categories.map((category) {
                      final isSelected = _selectedCategory == category['name'];
                      return Padding(
                        padding: const EdgeInsets.only(right: 8),
                        child: FilterChip(
                          label: Text(category['name']),
                          selected: isSelected,
                          onSelected: (selected) {
                            setState(() {
                              _selectedCategory =
                                  selected ? category['name'] : null;
                              _filterProducts();
                            });
                          },
                          backgroundColor: Colors.white.withOpacity(0.05),
                          selectedColor: const Color(
                            0xFF4BB4FF,
                          ).withOpacity(0.2),
                          labelStyle: TextStyle(
                            color:
                                isSelected
                                    ? const Color(0xFF4BB4FF)
                                    : Colors.white70,
                          ),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(20),
                            side: BorderSide(
                              color:
                                  isSelected
                                      ? const Color(0xFF4BB4FF)
                                      : Colors.transparent,
                            ),
                          ),
                        ),
                      );
                    }),
                  ],
                ),
              ),
            ],
          ),
        ),

        // Product List
        Expanded(
          child:
              _filteredProducts.isEmpty
                  ? Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.inventory_2_outlined,
                          size: 64,
                          color: Colors.white.withOpacity(0.1),
                        ),
                        const SizedBox(height: 16),
                        Text(
                          "No products found",
                          style: GoogleFonts.plusJakartaSans(
                            color: Colors.white38,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ],
                    ),
                  )
                  : ListView.builder(
                    padding: const EdgeInsets.fromLTRB(16, 0, 16, 100),
                    itemCount: _filteredProducts.length,
                    itemBuilder: (context, index) {
                      final product = _filteredProducts[index];
                      return Container(
                        margin: const EdgeInsets.only(bottom: 12),
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.05),
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(
                            color: Colors.white.withOpacity(0.05),
                          ),
                        ),
                        child: ListTile(
                          onTap: () => _showProductDetails(product),
                          contentPadding: const EdgeInsets.all(12),
                          leading: Container(
                            width: 50,
                            height: 50,
                            decoration: BoxDecoration(
                              color: Colors.white.withOpacity(0.05),
                              borderRadius: BorderRadius.circular(10),
                              image:
                                  product['image'] != null
                                      ? DecorationImage(
                                        image: NetworkImage(product['image']),
                                        fit: BoxFit.cover,
                                      )
                                      : null,
                            ),
                            child:
                                product['image'] == null
                                    ? const Icon(
                                      Icons.image_not_supported_outlined,
                                      color: Colors.white24,
                                    )
                                    : null,
                          ),
                          title: Text(
                            product['name'],
                            style: GoogleFonts.plusJakartaSans(
                              color: Colors.white,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          subtitle: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const SizedBox(height: 4),
                              Text(
                                product['category_name'] ?? 'Uncategorized',
                                style: GoogleFonts.plusJakartaSans(
                                  color: Colors.white38,
                                  fontSize: 12,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Row(
                                children: [
                                  Container(
                                    padding: const EdgeInsets.symmetric(
                                      horizontal: 8,
                                      vertical: 4,
                                    ),
                                    decoration: BoxDecoration(
                                      color:
                                          (product['current_stock'] ?? 0) > 10
                                              ? Colors.green.withOpacity(0.1)
                                              : Colors.red.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(6),
                                    ),
                                    child: Text(
                                      "${product['current_stock'] ?? 0} ${product['unit'] ?? ''}",
                                      style: GoogleFonts.plusJakartaSans(
                                        color:
                                            (product['current_stock'] ?? 0) > 10
                                                ? Colors.greenAccent
                                                : Colors.redAccent,
                                        fontSize: 10,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                          trailing: Text(
                            _formatCurrency(product['selling_price']),
                            style: GoogleFonts.plusJakartaSans(
                              color: const Color(0xFF4BB4FF),
                              fontWeight: FontWeight.bold,
                              fontSize: 14,
                            ),
                          ),
                        ),
                      );
                    },
                  ),
        ),
      ],
    );
  }
}

class ProductDetailsSheet extends StatefulWidget {
  final Map<String, dynamic> product;
  final List<dynamic> initialStocks;
  final String token;

  const ProductDetailsSheet({
    super.key,
    required this.product,
    required this.initialStocks,
    required this.token,
  });

  @override
  State<ProductDetailsSheet> createState() => _ProductDetailsSheetState();
}

class _ProductDetailsSheetState extends State<ProductDetailsSheet> {
  String _formatCurrency(dynamic amount) {
    final formatter = NumberFormat.currency(symbol: 'Tsh ', decimalDigits: 0);
    return formatter.format(amount ?? 0);
  }

  Widget _buildInfoRow(String label, String value, {Color? color}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: GoogleFonts.plusJakartaSans(color: Colors.white54),
          ),
          Text(
            value,
            style: GoogleFonts.plusJakartaSans(
              color: color ?? Colors.white,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height * 0.85,
      decoration: const BoxDecoration(
        color: Color(0xFF020B18),
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(24),
          topRight: Radius.circular(24),
        ),
        border: Border(top: BorderSide(color: Colors.white12)),
      ),
      child: Column(
        children: [
          // Handle bar
          Center(
            child: Container(
              margin: const EdgeInsets.only(top: 12, bottom: 20),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.white24,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),

          // Header
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            child: Row(
              children: [
                Container(
                  width: 60,
                  height: 60,
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.05),
                    borderRadius: BorderRadius.circular(12),
                    image:
                        widget.product['image'] != null
                            ? DecorationImage(
                              image: NetworkImage(widget.product['image']),
                              fit: BoxFit.cover,
                            )
                            : null,
                  ),
                  child:
                      widget.product['image'] == null
                          ? const Icon(
                            Icons.image_not_supported_outlined,
                            color: Colors.white24,
                          )
                          : null,
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        widget.product['name'],
                        style: GoogleFonts.plusJakartaSans(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        "${widget.product['category_name']} • SKU: ${widget.product['sku'] ?? 'N/A'}",
                        style: GoogleFonts.plusJakartaSans(
                          color: Colors.white54,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 6,
                  ),
                  decoration: BoxDecoration(
                    color: const Color(0xFF4BB4FF).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(
                      color: const Color(0xFF4BB4FF).withOpacity(0.2),
                    ),
                  ),
                  child: Text(
                    _formatCurrency(widget.product['selling_price']),
                    style: GoogleFonts.plusJakartaSans(
                      color: const Color(0xFF4BB4FF),
                      fontWeight: FontWeight.bold,
                      fontSize: 14,
                    ),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 24),

          Expanded(
            child: DefaultTabController(
              length: 2,
              child: Column(
                children: [
                  TabBar(
                    indicatorColor: const Color(0xFF4BB4FF),
                    labelColor: const Color(0xFF4BB4FF),
                    unselectedLabelColor: Colors.white54,
                    labelStyle: GoogleFonts.plusJakartaSans(
                      fontWeight: FontWeight.w600,
                    ),
                    tabs: const [
                      Tab(text: "Details"),
                      Tab(text: "Stock Batches"),
                    ],
                  ),
                  Expanded(
                    child: TabBarView(
                      children: [
                        // Details Tab
                        ListView(
                          padding: const EdgeInsets.all(24),
                          children: [
                            _buildInfoRow(
                              "Base Price",
                              _formatCurrency(widget.product['base_price']),
                            ),
                            _buildInfoRow(
                              "Selling Price",
                              _formatCurrency(widget.product['selling_price']),
                            ),
                            _buildInfoRow(
                              "Unit",
                              widget.product['unit'] ?? '-',
                            ),
                            _buildInfoRow(
                              "Total Quantity",
                              "${widget.product['current_stock']}",
                            ),
                            _buildInfoRow(
                              "Status",
                              widget.product['is_active'] == 1
                                  ? "Active"
                                  : "Inactive",
                              color:
                                  widget.product['is_active'] == 1
                                      ? Colors.greenAccent
                                      : Colors.redAccent,
                            ),
                          ],
                        ),

                        // Stock Batches Tab
                        widget.initialStocks.isEmpty
                            ? Center(
                              child: Text(
                                "No stock batches found.",
                                style: GoogleFonts.plusJakartaSans(
                                  color: Colors.white38,
                                ),
                              ),
                            )
                            : ListView.builder(
                              padding: const EdgeInsets.all(20),
                              itemCount: widget.initialStocks.length,
                              itemBuilder: (context, index) {
                                final stock = widget.initialStocks[index];
                                return Container(
                                  margin: const EdgeInsets.only(bottom: 12),
                                  padding: const EdgeInsets.all(16),
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.03),
                                    borderRadius: BorderRadius.circular(16),
                                    border: Border.all(color: Colors.white12),
                                  ),
                                  child: Row(
                                    mainAxisAlignment:
                                        MainAxisAlignment.spaceBetween,
                                    children: [
                                      Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            "Batch #${stock['id']}",
                                            style: GoogleFonts.plusJakartaSans(
                                              color: Colors.white70,
                                              fontSize: 12,
                                            ),
                                          ),
                                          const SizedBox(height: 4),
                                          Text(
                                            "Qty: ${stock['quantity']}",
                                            style: GoogleFonts.plusJakartaSans(
                                              color: Colors.white,
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ],
                                      ),
                                      if (stock['expiry_date'] != null)
                                        Container(
                                          padding: const EdgeInsets.symmetric(
                                            horizontal: 10,
                                            vertical: 6,
                                          ),
                                          decoration: BoxDecoration(
                                            color: Colors.redAccent.withOpacity(
                                              0.1,
                                            ),
                                            borderRadius: BorderRadius.circular(
                                              8,
                                            ),
                                          ),
                                          child: Text(
                                            "Exp: ${DateFormat('MMM dd, yyyy').format(DateTime.parse(stock['expiry_date']))}",
                                            style: GoogleFonts.plusJakartaSans(
                                              color: Colors.redAccent,
                                              fontSize: 11,
                                              fontWeight: FontWeight.w500,
                                            ),
                                          ),
                                        ),
                                    ],
                                  ),
                                );
                              },
                            ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
