import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:stockflowkp/services/api_service.dart';
import 'package:stockflowkp/services/database_service.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ProfitLossPage extends StatefulWidget {
  const ProfitLossPage({super.key});

  @override
  State<ProfitLossPage> createState() => _ProfitLossPageState();
}

class _ProfitLossPageState extends State<ProfitLossPage> {
  final ApiService _apiService = ApiService();
  final DatabaseService _dbService = DatabaseService();
  bool _isLoading = true;
  String? _error;
  Map<String, dynamic>? _plReport;
  String? _token;

  DateTime? _startDate;
  DateTime? _endDate;
  String _selectedRange = 'This Month';

  @override
  void initState() {
    super.initState();
    _setRange('This Month');
  }

  void _setRange(String range) {
    setState(() => _selectedRange = range);
    final now = DateTime.now();

    switch (range) {
      case 'Today':
        _startDate = now;
        _endDate = now;
        break;
      case 'Yesterday':
        final yesterday = now.subtract(const Duration(days: 1));
        _startDate = yesterday;
        _endDate = yesterday;
        break;
      case 'Last 7 Days':
        _startDate = now.subtract(const Duration(days: 6));
        _endDate = now;
        break;
      case 'This Month':
        _startDate = DateTime(now.year, now.month, 1);
        _endDate = now;
        break;
      case 'Last Month':
        final startOfLastMonth = DateTime(now.year, now.month - 1, 1);
        final endOfLastMonth = DateTime(now.year, now.month, 0);
        _startDate = startOfLastMonth;
        _endDate = endOfLastMonth;
        break;
    }
    _loadData(); // Re-fetch data when range changes
  }

  Future<void> _loadData() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final userData = await _dbService.getUserData();
      if (userData != null && userData['data'] != null) {
        _token = userData['data']['token'];

        final startStr =
            _startDate != null
                ? DateFormat('yyyy-MM-dd').format(_startDate!)
                : null;
        final endStr =
            _endDate != null
                ? DateFormat('yyyy-MM-dd').format(_endDate!)
                : null;

        final response = await _apiService.getConsolidatedProfitLoss(
          _token!,
          startDate: startStr,
          endDate: endStr,
        );

        if (mounted) {
          setState(() {
            _plReport = response['data'] ?? {};
            _isLoading = false;
          });
        }
      } else {
        if (mounted) {
          setState(() {
            _error = "User session not found.";
            _isLoading = false;
          });
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = "Failed to load report: $e";
          _isLoading = false;
        });
      }
    }
  }

  Future<void> _generatePdf() async {
    if (_plReport == null) return;

    final pdf = pw.Document();
    final summary = _plReport!['summary'];
    final expenseBreakdown = _plReport!['expense_breakdown'] as List? ?? [];
    final assets = _plReport!['assets'] ?? {};

    // Define custom colors
    final baseColor = PdfColors.blue900;
    final accentColor = PdfColors.blue600;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        footer: (pw.Context context) {
          return pw.Container(
            decoration: const pw.BoxDecoration(
              border: pw.Border(top: pw.BorderSide(color: PdfColors.grey400)),
            ),
            padding: const pw.EdgeInsets.only(top: 10),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by StockFlow',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          );
        },
        build: (pw.Context context) {
          return [
            // Header
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(color: baseColor, width: 2),
                ),
              ),
              padding: const pw.EdgeInsets.only(bottom: 10),
              margin: const pw.EdgeInsets.only(bottom: 20),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Profit & Loss Statement',
                        style: pw.TextStyle(
                          fontSize: 26,
                          fontWeight: pw.FontWeight.bold,
                          color: baseColor,
                        ),
                      ),
                      pw.Text(
                        'Period: $_selectedRange',
                        style: pw.TextStyle(fontSize: 16, color: accentColor),
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        'Date: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                      pw.Text(
                        'Time: ${DateFormat('HH:mm').format(DateTime.now())}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // Summary Section
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Column(
                children: [
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(
                        "Net Profit",
                        style: pw.TextStyle(
                          color: PdfColors.grey700,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.Text(
                        _formatCurrency(summary['net_profit']),
                        style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                          color:
                              (summary['net_profit'] ?? 0) >= 0
                                  ? PdfColors.green700
                                  : PdfColors.red700,
                        ),
                      ),
                    ],
                  ),
                  pw.SizedBox(height: 10),
                  pw.Divider(color: PdfColors.grey300),
                  pw.SizedBox(height: 10),
                  _buildPdfSummaryRow(
                    "Sales Revenue",
                    summary['sales_revenue'],
                  ),
                  pw.SizedBox(height: 5),
                  _buildPdfSummaryRow(
                    "Loan Repayments",
                    summary['loan_repayments'],
                  ),
                  pw.SizedBox(height: 5),
                  pw.Divider(color: PdfColors.grey200),
                  pw.SizedBox(height: 5),
                  _buildPdfSummaryRow(
                    "Total Revenue",
                    summary['total_revenue'] ?? summary['revenue'],
                    isBold: true,
                  ),
                  pw.SizedBox(height: 10),
                  _buildPdfSummaryRow("Cost of Goods", summary['cogs']),
                  pw.SizedBox(height: 5),
                  _buildPdfSummaryRow(
                    "Total Expenses",
                    summary['total_expenses'],
                  ),
                  pw.SizedBox(height: 5),
                  pw.Divider(color: PdfColors.grey300),
                  pw.SizedBox(height: 5),
                  _buildPdfSummaryRow(
                    "Gross Profit",
                    summary['gross_profit'],
                    isBold: true,
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Expense Breakdown
            pw.Text(
              "Expense Breakdown",
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: baseColor,
              ),
            ),
            pw.SizedBox(height: 10),
            if (expenseBreakdown.isEmpty)
              pw.Text(
                "No expenses recorded this period.",
                style: const pw.TextStyle(color: PdfColors.grey600),
              )
            else
              pw.Table.fromTextArray(
                context: context,
                headers: ['Category', 'Amount'],
                data:
                    expenseBreakdown.map((exp) {
                      return [
                        exp['category'] ?? 'Uncategorized',
                        _formatCurrency(exp['amount']),
                      ];
                    }).toList(),
                border: null,
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.white,
                ),
                headerDecoration: pw.BoxDecoration(color: baseColor),
                rowDecoration: const pw.BoxDecoration(
                  border: pw.Border(
                    bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                  ),
                ),
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.centerRight,
                },
              ),

            pw.SizedBox(height: 20),

            // Assets Valuation
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.blue50,
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    "Inventory Valuation",
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: baseColor,
                    ),
                  ),
                  pw.Text(
                    _formatCurrency(assets['inventory_valuation']),
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 14,
                      color: baseColor,
                    ),
                  ),
                ],
              ),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name:
          'Profit_Loss_Report_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf',
    );
  }

  pw.Widget _buildPdfSummaryRow(
    String label,
    dynamic amount, {
    bool isBold = false,
  }) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: PdfColors.grey800,
          ),
        ),
        pw.Text(
          _formatCurrency(amount),
          style: pw.TextStyle(
            fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: PdfColors.grey800,
          ),
        ),
      ],
    );
  }

  String _formatCurrency(dynamic amount) {
    final formatter = NumberFormat.currency(symbol: 'Tsh ', decimalDigits: 0);
    return formatter.format(amount ?? 0);
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Center(
        child: CircularProgressIndicator(color: Color(0xFF4BB4FF)),
      );
    }

    if (_error != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.error_outline, color: Colors.redAccent, size: 48),
            const SizedBox(height: 16),
            Text(
              _error!,
              textAlign: TextAlign.center,
              style: GoogleFonts.plusJakartaSans(color: Colors.white70),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: _loadData,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF4BB4FF),
              ),
              child: const Text("Retry"),
            ),
          ],
        ),
      );
    }

    if (_plReport == null) {
      return const Center(
        child: Text("No data available", style: TextStyle(color: Colors.white)),
      );
    }

    final summary = _plReport!['summary'];
    final expenseBreakdown = _plReport!['expense_breakdown'] as List? ?? [];
    final assets = _plReport!['assets'] ?? {};

    return SingleChildScrollView(
      physics: const AlwaysScrollableScrollPhysics(),
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildDateFilter(),

          const SizedBox(height: 16),
          Align(
            alignment: Alignment.centerRight,
            child: ElevatedButton.icon(
              onPressed: _generatePdf,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF4BB4FF),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 10,
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              icon: const Icon(Icons.picture_as_pdf, size: 18),
              label: const Text("Export PDF"),
            ),
          ),
          const SizedBox(height: 20),
          _buildSummaryCard(summary),
          const SizedBox(height: 24),
          Text(
            "Expense Breakdown",
            style: GoogleFonts.plusJakartaSans(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 16),
          if (expenseBreakdown.isEmpty)
            Text(
              "No expenses recorded this period.",
              style: GoogleFonts.plusJakartaSans(color: Colors.white54),
            )
          else
            ...expenseBreakdown.map((exp) => _buildExpenseRow(exp)).toList(),

          const SizedBox(height: 32),
          Text(
            "Assets Valuation",
            style: GoogleFonts.plusJakartaSans(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 16),
          _buildAssetCard(assets),
          // Add extra padding at bottom to ensure last items are visible
          const SizedBox(height: 80),
        ],
      ),
    );
  }

  Widget _buildSummaryCard(Map<String, dynamic> summary) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.05),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withOpacity(0.1)),
      ),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                "Net Profit",
                style: GoogleFonts.plusJakartaSans(
                  color: Colors.white70,
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 4,
                ),
                decoration: BoxDecoration(
                  color: (summary['gross_profit'] >= 0
                          ? Colors.green
                          : Colors.red)
                      .withOpacity(0.2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  "${summary['profit_margin']}% Margin",
                  style: GoogleFonts.plusJakartaSans(
                    color:
                        summary['gross_profit'] >= 0
                            ? Colors.greenAccent
                            : Colors.redAccent,
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Align(
            alignment: Alignment.centerLeft,
            child: Text(
              _formatCurrency(summary['net_profit']),
              style: GoogleFonts.plusJakartaSans(
                color:
                    summary['net_profit'] >= 0
                        ? Colors.greenAccent
                        : Colors.redAccent,
                fontSize: 28,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          const SizedBox(height: 24),
          _buildSummaryRow("Sales Revenue", summary['sales_revenue']),
          const SizedBox(height: 8),
          _buildSummaryRow("Loan Repayments", summary['loan_repayments']),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.05),
              borderRadius: BorderRadius.circular(8),
            ),
            child: _buildSummaryRow(
              "Total Revenue",
              summary['total_revenue'] ?? summary['revenue'],
              isPositive: true,
            ),
          ),
          const SizedBox(height: 8),
          _buildSummaryRow(
            "Cost of Goods (COGS)",
            summary['cogs'],
            isNegative: true,
          ),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 12),
            child: Divider(color: Colors.white12),
          ),
          _buildSummaryRow("Gross Profit", summary['gross_profit']),
          const SizedBox(height: 8),
          _buildSummaryRow(
            "Total Expenses",
            summary['total_expenses'],
            isNegative: true,
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryRow(
    String label,
    dynamic amount, {
    bool isNegative = false,
    bool isPositive = false,
  }) {
    Color amountColor = Colors.white;
    if (isNegative) amountColor = Colors.redAccent.withOpacity(0.8);
    if (isPositive) amountColor = Colors.greenAccent.withOpacity(0.8);

    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: GoogleFonts.plusJakartaSans(
            color: Colors.white60,
            fontSize: 12,
          ),
        ),
        Text(
          (isNegative ? "- " : "") + _formatCurrency(amount),
          style: GoogleFonts.plusJakartaSans(
            color: amountColor,
            fontSize: 13,
            fontWeight: FontWeight.w600,
          ),
        ),
      ],
    );
  }

  Widget _buildExpenseRow(Map<String, dynamic> expense) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.05),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Colors.orangeAccent.withOpacity(0.1),
                  shape: BoxShape.circle,
                ),
                child: const Icon(
                  Icons.receipt_long_rounded,
                  color: Colors.orangeAccent,
                  size: 16,
                ),
              ),
              const SizedBox(width: 12),
              Text(
                expense['category'] ?? 'Uncategorized',
                style: GoogleFonts.plusJakartaSans(
                  color: Colors.white,
                  fontWeight: FontWeight.w500,
                  fontSize: 13,
                ),
              ),
            ],
          ),
          Text(
            _formatCurrency(expense['amount']),
            style: GoogleFonts.plusJakartaSans(
              color: Colors.white,
              fontWeight: FontWeight.bold,
              fontSize: 13,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAssetCard(Map<String, dynamic> assets) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF4BB4FF).withOpacity(0.1),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF4BB4FF).withOpacity(0.2)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: const Color(0xFF4BB4FF).withOpacity(0.2),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.inventory_2_outlined,
              size: 20,
              color: Color(0xFF4BB4FF),
            ),
          ),
          const SizedBox(width: 16),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                "Inventory Valuation",
                style: GoogleFonts.plusJakartaSans(
                  color: const Color(0xFF4BB4FF).withOpacity(0.8),
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 2),
              Text(
                _formatCurrency(assets['inventory_valuation']),
                style: GoogleFonts.plusJakartaSans(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildDateFilter() {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Row(
        children: [
          _filterChip('Today'),
          const SizedBox(width: 8),
          _filterChip('Yesterday'),
          const SizedBox(width: 8),
          _filterChip('Last 7 Days'),
          const SizedBox(width: 8),
          _filterChip('This Month'),
          const SizedBox(width: 8),
          _filterChip('Last Month'),
        ],
      ),
    );
  }

  Widget _filterChip(String label) {
    final isSelected = _selectedRange == label;
    return GestureDetector(
      onTap: () => _setRange(label),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
          color:
              isSelected
                  ? const Color(0xFF4BB4FF)
                  : Colors.white.withOpacity(0.05),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color:
                isSelected
                    ? const Color(0xFF4BB4FF)
                    : Colors.white.withOpacity(0.1),
          ),
        ),
        child: Text(
          label,
          style: GoogleFonts.plusJakartaSans(
            color: isSelected ? Colors.white : Colors.white70,
            fontSize: 12,
            fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
          ),
        ),
      ),
    );
  }
}
